# Weather Observation Station 5

(
    SELECT CITY, CHAR_LENGTH(CITY) AS LENGTH
    FROM STATION
    ORDER BY LENGTH ASC, CITY ASC
    LIMIT 1
)
UNION
(
    SELECT CITY, CHAR_LENGTH(CITY) AS LENGTH
    FROM STATION
    ORDER BY LENGTH DESC, CITY ASC
    LIMIT 1
);